services:
  # Nosso banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: phmetro_db
    env_file:
      - ../.env
    environment:
      # Definimos uma senha root e o nome do banco
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      # Mantém os dados salvos mesmo se o container for apagado
      - db_data:/var/lib/mysql
      # Pega o seu banco.sql na pasta raiz do projeto (voltou uma pasta: ../) e executa
      - ../banco.sql:/docker-entrypoint-initdb.d/banco.sql
    ports:
      # Permite acessar o banco na porta configurada no .env
      - "${DOCKER_DB_PORT:-3306}:3306"

  # Nosso servidor com PHP e o site
  web:
    build: 
      # Aponta o contexto de construção para a raiz do projeto para o Dockerfile conseguir copiar os arquivos de lá
      context: ..
      # Aponta onde está o arquivo Dockerfile
      dockerfile: docker/Dockerfile
    container_name: phmetro_web
    ports:
      # O site vai ficar acessível na porta configurada no .env
      - "${DOCKER_WEB_PORT:-9002}:90"
    env_file:
      - ../.env
    environment:
      # Sobrescrevemos apenas o DB_HOST para conectar no container do banco
      DB_HOST: db
    depends_on:
      # Garante que o web só sobe depois que o banco (db) já subiu
      - db
    volumes:
      # Espelha a sua pasta raiz do projeto (../) para dentro do container
      - ../:/var/www/html/

volumes:
  db_data:

